trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'PAYG (personal)'
    ScriptType: 'FilePath'
    ScriptPath: 'cleanup.ps1'
    ScriptArguments: '-Tag "test"'
    pwsh: true
