schedules:
- cron: "*/5 * * * *"
  displayName: "hourly cleanup"
  branches:
    include:
    - master
  always: "true"

pool:
  vmImage: 'windows-2019'

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'PAYG (personal)'
    ScriptType: 'FilePath'
    ScriptPath: 'cleanup.ps1'
    ScriptArguments: '-Tag "test"'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
