schedules:
- cron: "0 */3 * * *"
  displayName: "every 3 hours cleanup"
  branches:
    include:
    - master
  always: "true"

pool:
  vmImage: 'windows-2019'

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'PAYG (personal)'
    ScriptType: 'FilePath'
    ScriptPath: 'cleanup.ps1'
    ScriptArguments: '-DeleteMe'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
